Updated quickstart scripts to use the latest quickstart module
cloudera-labs/cdp-tf-quickstarts pull request #15
Opened 2024-02-01 12:20 UTC by daszabo

2024-02-01 13:12 UTC, jimright requested changes
@daszabo,

This all looks good. Just added one suggestion about how we might handle a default value for the deployment template input variable.

2024-02-01 13:12 UTC, jimright commented on aws/quickstart.sh
> +export TF_VAR_deployment_template="${3:-""}"
We could default to semi-private deployment template with something like the below. This would make the final argument to the script optional.
```
export TF_VAR_deployment_template="${3:-"semi-private"}"
```

2024-02-01 13:46 UTC, balazsgaspar commented on aws/quickstart.sh
> +export TF_VAR_deployment_template="${3:-""}"
+1 for defaulting to semi-private for all three clouds

2024-02-01 13:46 UTC, balazsgaspar commented on aws/quickstart.sh
> +export TF_VAR_deployment_template="${3:-""}"
(and making the input variable optional)

2024-02-02 12:15 UTC, jimright approved these changes
Looks good. Approved.

2024-02-02 12:15 UTC, merged